services:
  whisper:
    image: transcription-server-whisper-gpu:local
    build:
      context: .
      dockerfile: docker/nvidia/Dockerfile
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

volumes:
  whisper-model-cache:
    external: false
    name: ${WHISPER_MODEL_CACHE_VOLUME_NAME:-transcription-server-whisper-data}
